# Generated by Django 4.0.8 on 2023-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookWorld', '0003_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='static/img/book.png', null=True, upload_to='images/'),
        ),
    ]
