# Generated by Django 4.0.8 on 2023-02-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookWorld', '0006_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=225),
        ),
    ]
